/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.42
 * Generated at: 2017-07-10 04:45:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>用户注册</title>\r\n");
      out.write("<script>\r\n");
      out.write("function checkusername()\r\n");
      out.write("{\r\n");
      out.write("\tvar username1=document.form3.reg_username.value;\r\n");
      out.write("\tif(username1==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\talert(\"请输入用户名！\")\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("    if(username1.length<2||username1.length>10)\r\n");
      out.write("\t{\r\n");
      out.write("\talert(\"用户名必须超过2位或者小于11位！\");\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function checkpassword()\r\n");
      out.write("{\r\n");
      out.write("\tvar password1=document.form3.reg_pswd.value;\r\n");
      out.write("\tif(password1==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\talert(\"请输入密码！\")\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("if(password1.length<5)\r\n");
      out.write("\t{\r\n");
      out.write("\talert(\"密码必须大于6位！\")\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("if(password1.length>20)\r\n");
      out.write("\t{\r\n");
      out.write("\talert(\"密码必须小于20位！\")\r\n");
      out.write("\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function checktel()\r\n");
      out.write("{\r\n");
      out.write("\tvar tel1=document.form3.tel.value;\r\n");
      out.write("\tif(tel1==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"请输入电话号码！\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(tel1.length!=11)\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"电话号码格式输入不正确！\")\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("function checkall()\r\n");
      out.write("{\r\n");
      out.write("\tif(checkusername()&&checkpassword()&&checktel())\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\telse\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"image/bg1.jpg\">\r\n");
      out.write("\r\n");
      out.write("<font face=\"楷体\" size=\"4\">\r\n");
      out.write("<h2 align=\"center\">注册信息</h2>\r\n");
      out.write("    <form id=\"form3\" name=\"form3\" action=\"register\" method=\"post\" onsubmit=\"return checkall()\">\r\n");
      out.write("       <table width=\"500\" border=\"1\" cellspacing=\"0\" cellpadding=\"10\" align=\"center\" >\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"30%\" align=\"right\">姓名：</td>\r\n");
      out.write("              <td width=\"70%\"><input type=\"text\" name=\"reg_username\" id=\"textfield\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td align=\"right\">密码：</td>\r\n");
      out.write("              <td><input type=\"password\" name=\"reg_pswd\" id=\"pswd\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("              <td align=\"right\">性别：</td>\r\n");
      out.write("              <td><input type=\"radio\" name=\"radio\" checked value=\"man\">男\r\n");
      out.write("                  <input type=\"radio\" name=\"radio\" value=\"woman\">女</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("              <td align=\"right\">备注：</td>\r\n");
      out.write("              <td><input type=\"text\" name=\"beizhu\" id=\"beizhu\" ></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td align=\"right\">联系电话：</td>\r\n");
      out.write("              <td><input type=\"text\" name=\"tel\" id=\"tel\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          \r\n");
      out.write("            <tr>\r\n");
      out.write("              <td colspan=\"2\" align=\"center\"><input type=\"submit\" name=\"submit\" id=\"submit\" value=\"注册\"> \r\n");
      out.write("               &nbsp;&nbsp;&nbsp;&nbsp; <input type=\"reset\" name=\"reset\" id=\"reset\" value=\"重置\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("       </table>\r\n");
      out.write("    </form>\r\n");
      out.write("</font>\r\n");
      out.write("<br><br><br><br><br><br><br><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
