/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.42
 * Generated at: 2017-07-11 01:29:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Auto_005ftickets_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>自助购票</title>\r\n");
      out.write("    <link href=\"dzsw/style/style.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"dzsw/style/layer.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"dzsw/style/yuding.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"dzsw/style/easyAlert.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"dzsw/scripts/jquery-1.7.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"dzsw/scripts/jquery.cookie.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"hello()\">\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("    <div class=\"logo\"><br><br><br><br>\r\n");
      out.write("        <img style=\"float: left; width: 52px; height: 52px;\"\r\n");
      out.write("             src=\"dzsw/images/icon.png\"/>\r\n");
      out.write("        <div align=\"left\">\r\n");
      out.write("            <font size=\"6\" face=\"黑体\">网上火车订票系统</font>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"top\" style=\"text-align: right\">\r\n");
      out.write("        <font size=\"4\" face=\"楷体\" color=\"blue\">\r\n");
      out.write("            <strong id=\"hello\"></strong><strong class=\"red\" id=\"islogin\"><a\r\n");
      out.write("                href=\"login.jsp\"> 请登录...</a></strong></font>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nav\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"index.jsp\">首 页</a></li>\r\n");
      out.write("            <li><a href=\"Auto_tickets.jsp\">自助购票</a></li>\r\n");
      out.write("            <li><a href=\"login.jsp\">个人中心</a></li>\r\n");
      out.write("            <li><a href=\"failure_orders.jsp\">订单查询</a></li>\r\n");
      out.write("            <li><a href=\"help.jsp\"> 帮助信息</a></li>\r\n");
      out.write("            <li class=\"date\">\r\n");
      out.write("                <script src=\"dzsw/scripts/chdata.js\"></script>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--头部结束-->\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--中部开始-->\r\n");
      out.write("<div id=\"homeWrap\">\r\n");
      out.write("    <div class=\"container bs1\">\r\n");
      out.write("        <div class=\"ydbox\">\r\n");
      out.write("            <!--进度-->\r\n");
      out.write("            <div class=\"ydjd1\">班次查询</div>\r\n");
      out.write("            <div class=\"ydfromcx\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><em>始发地</em><input type=\"text\" style=\"color: #999999;\"\r\n");
      out.write("                                           name=\"reachstationname\" value=\"慈溪\"\r\n");
      out.write("                                           onclick=\"GetCityList(this, 1);$('#city').val('');\"\r\n");
      out.write("                                           onkeyup=\"selCity(event);\" id=\"reachCity\" tabindex=\"1\"\r\n");
      out.write("                                           class=\"inputU\"></li>\r\n");
      out.write("                    <li><em>目的地</em><input type=\"text\" style=\"color: #999999;\"\r\n");
      out.write("                                           value=\"--\"\r\n");
      out.write("                                           onfocus=\"if(this.value=='请输入简拼/全拼/汉字'){this.value='';this.style.color='#333';}\"\r\n");
      out.write("                                           onblur=\"if(!this.value){this.value='请输入简拼/全拼/汉字';this.style.color='#999999'}\"\r\n");
      out.write("                                           name=\"s_cities\" autocomplete=\"off\"\r\n");
      out.write("                                           onclick=\"this.value = ''; GetEndstation(this);  \"\r\n");
      out.write("                                           onkeyup=\"selCity(event)\" id=\"city\" tabindex=\"2\" class=\"inputU\"></li>\r\n");
      out.write("\r\n");
      out.write("                    <li><em>发车时间</em><input type=\"text\"\r\n");
      out.write("                                            onClick=\"WdatePicker({minDate:'2017-07-10 ',maxDate:'2017-07-17'})\"\r\n");
      out.write("                                            id=\"starttime\"\r\n");
      out.write("                                            onfocus=\"if(this.value=='例如：2014-08-14'){this.value='';this.style.color='#333';}\"\r\n");
      out.write("                                            onblur=\"if(!this.value){this.value='例如：2014-08-14';this.style.color='#999999'}\"\r\n");
      out.write("                                            tabindex=\"3\" class=\"inputU\"/></li>\r\n");
      out.write("                    <li style=\"width: 150px;\">\r\n");
      out.write("                        <a onclick=\"showcomlogin();\"\r\n");
      out.write("                           href=\"javascript:;\" class=\"button1 input-cx1\" id=\"search_sub1\">立即查询</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clear\"></div>\r\n");
      out.write("            <div class=\"datediv\" id=\"datebag\"></div>\r\n");
      out.write("            <div class=\"yddiv1\">\r\n");
      out.write("                <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td width=\"200\" align=\"left\" style=\"text-indent: 2em;\"\r\n");
      out.write("                            id=\"starttime2\">出发时间：\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td width=\"150\"><span> <input name=\"timeBucket\"\r\n");
      out.write("                                                      type=\"checkbox\" checked=\"checked\" id=\"amcheck\"\r\n");
      out.write("                                                      onclick=\"showcomlogin();\"/> 上午\r\n");
      out.write("\t\t\t\t\t\t\t</span> (00:00 - 12:00 )\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td width=\"150\"><span> <input name=\"timeBucket\"\r\n");
      out.write("                                                      type=\"checkbox\" checked=\"checked\" id=\"pmcheck\"\r\n");
      out.write("                                                      onclick=\"showcomlogin();\"/> 下午\r\n");
      out.write("\t\t\t\t\t\t\t</span> ( 12:01 -23:59 )\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form id=\"form1\" action=\"reg\" method=\"post\">\r\n");
      out.write("                <input name=\"__RequestVerificationToken\" type=\"hidden\"\r\n");
      out.write("                       value=\"3BsdkUe8LB3q8Zi77dPP30v9ri3g6LQ7eLRcAWnrotX_iZ2lTZzI7PCAUCsUv1rEM7xvb4BiyXnfdYC2poF_PQ2\"/>\r\n");
      out.write("                <div class=\"yddiv2\" id=\"bclist\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <table width=\"100%\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                        <tr id=\"rowinof\" class=\"tt\">\r\n");
      out.write("                            <th width=\"30\" scope=\"col\" align=\"center\">序号</th>\r\n");
      out.write("                            <th width=\"80\" scope=\"col\" align=\"center\">发车时间</th>\r\n");
      out.write("                            <th width=\"80\" align=\"center\">车次代码</th>\r\n");
      out.write("                            <th width=\"160\" align=\"center\" scope=\"col\">线路名称</th>\r\n");
      out.write("                            <th width=\"119\" scope=\"col\" align=\"center\">上车站</th>\r\n");
      out.write("                            <th width=\"119\" scope=\"col\" align=\"center\">到达站</th>\r\n");
      out.write("\r\n");
      out.write("                            <th width=\"65\" scope=\"col\" align=\"center\">客别</th>\r\n");
      out.write("                            <th width=\"90\" scope=\"col\" align=\"center\">车型</th>\r\n");
      out.write("                            <th width=\"120\" scope=\"col\" align=\"center\">\r\n");
      out.write("                                <a id=\"pj\"\r\n");
      out.write("                                   href=\"javascript:void(0)\"\r\n");
      out.write("                                   onclick=\"scheduleStor('discountprice',this)\"\r\n");
      out.write("                                   class=\"input-piaojia\"><span>票价(全)</span> </a>\r\n");
      out.write("                            </th>\r\n");
      out.write("                            <th width=\"120\" scope=\"col\" align=\"center\">余座(携)</th>\r\n");
      out.write("                            <th width=\"100\" align=\"center\" scope=\"col\"></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--中部结束-->\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--中部结束-->\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"layer1\" style=\"z-index: 19891016; display: none;\">\r\n");
      out.write("    <div times=\"1\" id=\"xubox_shade2\" class=\"xubox_shade\"\r\n");
      out.write("         style=\"z-index: 19891016; background-color: #000; opacity: 0.3; filter: alpha(opacity = 30);\"></div>\r\n");
      out.write("    <div times=\"1\" showtime=\"0\"\r\n");
      out.write("         style=\"z-index: 19891016; left: 50%; top: 121.5px; width: 380px; height: 300px; margin-left: -190px;\"\r\n");
      out.write("         id=\"xubox_layer1\" class=\"xubox_layer\" type=\"page\">\r\n");
      out.write("        <div style=\"background-color: #fff; z-index: 19891015\"\r\n");
      out.write("             class=\"xubox_main\">\r\n");
      out.write("            <div class=\"xubox_page\" style=\"top: 36px;\">\r\n");
      out.write("                <div style=\"\" id=\"touch_lo\" class=\"layer_pageContent\">\r\n");
      out.write("                    <div class=\"Pop-up_logoin\" style=\"background: none\">\r\n");
      out.write("                        <form target=\"supportiframe\"\r\n");
      out.write("                              action=\"index.php?m=login&amp;c=loginsave\" method=\"post\">\r\n");
      out.write("                            <div class=\"Pop-up_logoin_list\">\r\n");
      out.write("                                <span>用户名：</span> <input type=\"text\" id=\"username\" value=\"\"\r\n");
      out.write("                                                         tabindex=\"91\" name=\"username\" class=\"ajax_login_input\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"Pop-up_logoin_list\">\r\n");
      out.write("                                <span>密 码：</span> <input type=\"password\" id=\"password\"\r\n");
      out.write("                                                         tabindex=\"92\" name=\"password\" value=\"\"\r\n");
      out.write("                                                         class=\"ajax_login_input\" onkeydown=\"javascrip:fastLogin()\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"Pop-up_logoin_list\">\r\n");
      out.write("                                <span>验证码：</span> <input id=\"authcode\" type=\"text\"\r\n");
      out.write("                                                         tabindex=\"93\" style=\"width: 60px;\" maxlength=\"4\"\r\n");
      out.write("                                                         name=\"authcode\" class=\"ajax_login_input w60\"\r\n");
      out.write("                                                         onkeydown=\"javascrip:fastLogin()\"> <img\r\n");
      out.write("                                    src=\"/dzsw/Validate.ashx\" name=\"vcode_img\" width=\"60\"\r\n");
      out.write("                                    height=\"30\" id=\"vcode_img\"\r\n");
      out.write("                                    style=\"margin-right: 5px; margin-left: 5px;\">&nbsp;<a\r\n");
      out.write("                                    href=\"javascript:check_code();\">换一张</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"Pop-up_logoin_list\">\r\n");
      out.write("                                <div id=\"msg\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"Pop-up_logoin_list\">\r\n");
      out.write("                                <span>&nbsp;</span>\r\n");
      out.write("                                <!--<input id=\"loginsubmit\" class=\"login_button\" type=\"button\" name=\"loginsubmit\" onclick=\"checkcomlogin()\">-->\r\n");
      out.write("                                <a id=\"loginsubmit\" class=\"login_button\"\r\n");
      out.write("                                   href=\"javascript:checklogin();\">登录</a> <a\r\n");
      out.write("                                    href=\"/dzsw/forgetpwd/index\" class=\"lh65\">忘记密码？</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"Pop-up_logoin_bot\">\r\n");
      out.write("                            <span>&nbsp;</span> 还没有账号？<a href=\"/dzsw/register/index\"\r\n");
      out.write("                                                         target=\"_blank\" class=\"Orange\">免费注册</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"xubox_title\" move=\"ok\" style=\"cursor: move;\">\r\n");
      out.write("                <em>快速登录</em>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"xubox_setwin\"><a\r\n");
      out.write("                    class=\"xubox_close xulayer_png32 xubox_close0\" id=\"xubox_close1\"\r\n");
      out.write("                    href=\"javascript:;\" style=\"\"></a></span><span class=\"xubox_botton\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"xubox_border1\" class=\"xubox_border\"\r\n");
      out.write("             style=\"z-index: 19891014; background-color: rgb(0, 0, 0); opacity: 0.3; top: -10px; left: -10px; width: 400px; height: 320px;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--尾部开始-->\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"Copyright\">湖北省武汉理工大学 版权所有&copy; 2017 技术支持<a href=\"/dzsw/logger.aspx \">:</a><a\r\n");
      out.write("            href=\"http://www.zjeasy.com/\" target=\"_blank\">长沙最终幻想软件股份有限公司</a> <span>程序版本: 2.0.16.329</span><br/>\r\n");
      out.write("        购票服务电话:0574-63810109 ICP备案号：湘ICP备05064785\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--尾部结束-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
